apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ljqk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ljqk
    app.kubernetes.io/part-of: byoc-app-btew
  name: ljqk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: ljqk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: ljqk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-yccy-tenant/byoc-app-btew/ljqk@sha256:07d3bc1a7291c7ac3ee146756039bd0cfd44d123a24d23aec95896d411811fd1
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
